M48
; DRILL file KiCad 10.0.1 date 2026-04-17T14:45:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-17T14:45:51-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X136.925Y-88.675
X146.225Y-74.175
T2
X166.04Y-90.23
M30
